# Build-time helper: compile one GLSL shader to SPIR-V and emit a C++ header that
# embeds the words (VULKAN-TODO.md §5 V2 / §7.2).
#
# Run as a script, driven by CMakeLists.txt:
#   cmake -DHMRDP_GLSLANG=<glslang_validator> \
#         -DHMRDP_SRC=<shader.comp> \
#         -DHMRDP_OUT=<generated header> \
#         -DHMRDP_SYMBOL=<C++ symbol> \
#         [-DHMRDP_INCLUDE=<dir>] \
#         -P cmake/EmbedSpirv.cmake
#
# HMRDP_INCLUDE is optional and only needed by a shader that #includes a header
# (the FSR passes pull in the vendored ffx_fsr1.h).
#
# Embedding (rather than shipping .spv files next to the .so) keeps the runtime
# free of file IO and makes "SPIR-V travels with the HAP" automatic: the words are
# part of libhmrdp.so, so packaging cannot silently miss them.

foreach(required HMRDP_GLSLANG HMRDP_SRC HMRDP_OUT HMRDP_SYMBOL)
  if(NOT DEFINED ${required})
    message(FATAL_ERROR "EmbedSpirv: ${required} is required")
  endif()
endforeach()

if(NOT EXISTS "${HMRDP_GLSLANG}")
  message(FATAL_ERROR "EmbedSpirv: glslang_validator not found at ${HMRDP_GLSLANG}")
endif()

get_filename_component(_outDir "${HMRDP_OUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_outDir}")

set(_spv "${HMRDP_OUT}.spv")
# The include flag has to be a single token with no space ("-I<dir>"), and an
# unquoted empty variable expands to no argument at all.
set(_include "")
if(DEFINED HMRDP_INCLUDE AND NOT "${HMRDP_INCLUDE}" STREQUAL "")
  set(_include "-I${HMRDP_INCLUDE}")
endif()
execute_process(
  COMMAND "${HMRDP_GLSLANG}" -V --target-env vulkan1.1 ${_include} -o "${_spv}" "${HMRDP_SRC}"
  RESULT_VARIABLE _rc
  OUTPUT_VARIABLE _stdout
  ERROR_VARIABLE _stderr)
if(NOT _rc EQUAL 0)
  message(FATAL_ERROR
          "EmbedSpirv: glslang_validator failed (${_rc}) for ${HMRDP_SRC}\n${_stdout}\n${_stderr}")
endif()

# SPIR-V is a stream of 32-bit words. `file(READ ... HEX)` yields the file's bytes
# in file order, i.e. little-endian byte order on disk, so each 4-byte group has
# to be reversed to get the numeric word value a uint32_t array must hold
# (otherwise the SPIR-V magic comes out as 0x03022307 instead of 0x07230203 and
# vkCreateShaderModule rejects the module).
file(READ "${_spv}" _hex HEX)
string(LENGTH "${_hex}" _hexLength)
math(EXPR _wordCount "${_hexLength} / 8")
string(REGEX REPLACE "([0-9a-fA-F][0-9a-fA-F])([0-9a-fA-F][0-9a-fA-F])([0-9a-fA-F][0-9a-fA-F])([0-9a-fA-F][0-9a-fA-F])"
                     "0x\\4\\3\\2\\1, " _words "${_hex}")

# Fail loudly rather than embedding something the driver will reject later.
string(SUBSTRING "${_hex}" 0 8 _magicBytes)
string(SUBSTRING "${_magicBytes}" 6 2 _m0)
string(SUBSTRING "${_magicBytes}" 4 2 _m1)
string(SUBSTRING "${_magicBytes}" 2 2 _m2)
string(SUBSTRING "${_magicBytes}" 0 2 _m3)
if(NOT "${_m0}${_m1}${_m2}${_m3}" STREQUAL "07230203")
  message(FATAL_ERROR "EmbedSpirv: ${HMRDP_SRC} did not compile to SPIR-V (bad magic)")
endif()

file(WRITE "${HMRDP_OUT}"
"// Generated by cmake/EmbedSpirv.cmake from ${HMRDP_SRC} - do not edit.
#pragma once

#include <cstdint>

namespace hmrdp {

static const uint32_t k${HMRDP_SYMBOL}Spv[] = { ${_words} };
static const uint32_t k${HMRDP_SYMBOL}SpvWords = ${_wordCount}u;

}  // namespace hmrdp
")
